### ISSUE TITLE
evals research notebook

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#50]
extending #13 
add an option to sample prompts from a (range of quantiles) distribution of loss difference between two models
get a minimal working version quickly before adding any complex functionality
but write some library code when it makes sense
![image](https://github.com/delphi-suite/delphi/assets/17082351/00c8d2a5-c612-4282-bd7a-33f693028a2e)

**Comment by menamerai** [comment]
Later thought: histogram of distribution to choose from to sample prompts.

**Comment by menamerai** [comment]
Visualization of system
![Research Notebook](https://github.com/delphi-suite/delphi/assets/62800649/6bf6c332-8ec0-42ba-a41c-3a1e8fee09d3)

**Comment by menamerai** [comment]
Todos:

- [x] Pull loss data from HF and perform diff on them
- [x] Choose quantile from user option
- [x] Sample prompt from those quantile and display up to the diff token
    - [x]  Sample prompt from quantile.
    - [x] Modify display script to display up to specific token.
- [x] Wrangle with types and positioning to get the final demo up and running

**Comment by jettjaniak** [comment]
*quantile

**Comment by menamerai** [comment]
@jettjaniak @transcendingvictor should I know from which prompts [these logprobs](https://huggingface.co/datasets/delphi-suite/v0-next-logprobs-llama2-100k) are from? I need to know which prompts they're from to get the token_ids and visualize the tokens.

**Comment by transcendingvictor** [comment]
They were based on the tokenized validation dataset available in [huggingface ](https://huggingface.co/datasets/delphi-suite/v0-tinystories-v2-clean-tokenized), which is basically the storyes from TinyStories, tokenized and grouped in batches of 513 token-ids I believe. Thus, the logprobs start with "None" because there's no prediction from the model for the fisrt token so there is no "correct prediction".

So the promts is the validation [dataset ](https://huggingface.co/datasets/delphi-suite/tinystories-v2-clean), which is already tokenized (in the first link).

Does this answer your question?
