### ISSUE TITLE
update beartype to 0.18

### ISSUE THREAD

**Issue by jettjaniak** [delphi-suite/delphi#57]
it's is not checking whether keys or values of your dict are of correct type, we need to read about it and how to fix it

start with reproducing the issue by making a test that won't fail even though the type hints are wrong

then fix the issue globally and submit a PR

**Comment by jaidhyani** [comment]
Looks like it's not supported atm, but they're hoping to implement it "this year". That said, it looks like this has been an aspiration for at least three years now, so we probably don't want to wait. https://github.com/beartype/beartype/issues/53

For now, what if we wrap key dicts in typed classes with `get` and `set` functions?

There is `TypedDict` for cases with static keys - but in those cases we should probably just be defining a class anyway, especially since `TypedDict` doesn't really do much on its own and it more of a desperate plea to third parties to implement a deep type-checking solution.

**Comment by leycec** [comment]
**@beartype maintainer @leycec has been summoned to the chat.** Coincidentally, I *just* nailed this tonight. Apologies for the excruciating wait. It was worth it. I swear! Would a guy on GitHub lie? The upcoming @beartype 0.18.0 release deeply type-checks all dictionary type hints in `O(1)` time – which is to say, stupidly fast. [See this for further commentary](https://github.com/beartype/beartype/issues/53#issuecomment-1996561183).

I intend to drop 0.18.0 this Friday evening. Let us pretend that I keep my promises. :crossed_fingers:

**Comment by jaidhyani** [comment]
Holy crap. I was a fool to doubt.

**Comment by jaidhyani** [comment]
@leycec Congrats on 0.18!

**Comment by leycec** [comment]
Thanks so much, @jaidhyani! Please ping me if you hit any snags with dictionary type-checking or just wish @beartype did something better for @delphi-suite. We all wish @beartype was better, too. :smile_cat:
